### ISSUE TITLE
Problems importing the eww widget dashboard into my own config

### ISSUE THREAD

**Issue by AzhamProdLive** [hidayry/dotfiles-bspwm#2]
Hello there, as the title states, I am trying to import your dashboard widget.
I have taken the dashboard file, variables.yuck and the colors.scss inside my own bspwm config, and tried to run it after doing the edits needed for it to run, but this is what I get 
![image](https://github.com/hidayry/dotfiles-bspwm/assets/73955243/35ffe159-49b5-474a-b9fd-924e61082cd3)
instead of something like you have too : 
![image](https://github.com/hidayry/dotfiles-bspwm/assets/73955243/24b70da9-8613-4f20-839c-1bc2a67e8fdd)

My main question would be, do you have any ideas why it does that ? and maybe any possible fixes in order to get the end product ? Thanks in advance

**Comment by hidayry** [comment]
Use my eww,, 

Don't use eww from your build..

**Comment by AzhamProdLive** [comment]
> Use my eww,,
> 
> Don't use eww from your build..

Understood, I'll try that and report back, thanks for your reply 😄
